public class Constants {
  public static final String PHYSICAL_OFFER = 'physical';
  public static final String TEST_ACCOUNT = 'Test acc';
  public static final String TEST_SALON = 'Test salon';
  public static final String TEST_VEHICLE_MODEL = 'Astra';
  public static final String TEST_VEHICLE_BRAND = 'Opel';
  public static final String TEST_TELEMETRY_NAME = 'TEST telemetry';
  public static final String TEST_OFFER_NAME = 'TEST offer';
  public static final String DELETED_TELEMETRY = 'TELEMETRY DELETED';
  public static final String SALON_CLOSED_STATUS = 'close';
  public static final String CONNECTION_FAILED = 'Blad polaczenia';
  public static final String CASE_ENDPOINT = 'https://jsonplaceholder.typicode.com/posts';
  public static final String CASE_METHOD = 'POST';
  public static final String CASE_CLOSED_STATUS = 'Closed';
  public static final String CASE_FAILD_STATUS = 'Faild';
  public static final String RENOVATION_CASE = 'Renovation Case ';
  public static final String CONNECTION_FAILED_MESSAGE = 'Connection failed';
  public static final String CONTENT_TYPE = 'Content-Type';
  public static final String JSON_TYPE = 'application/json';
  public static final String EMAIL_SUBJECT = 'Nowa oferta';
  public static final String OFFER_NAME = 'nazwa oferty:';
  public static final String CRON = '0 0 0 1 7 ? *';
}
