public class Constants {

    public static final String PHYSICAL_OFFER = 'physical';
    public static final String TEST_ACCOUNT = 'Test acc';
    public static final String TEST_SALON = 'Test salon';
    public static final String TEST_VEHICLE_MODEL = 'Astra';
    public static final String TEST_VEHICLE_BRAND = 'Opel';
    public static final String TEST_TELEMETRY_NAME = 'TEST telemetry';
    public static final String TEST_OFFER_NAME = 'TEST offer';


    
}